version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: freddyBlack
      POSTGRES_PASSWORD: Freddyblack20054*
      POSTGRES_DB: paquefreddy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/paquefreddy
    ports:
      - "3001:3001"
    command: ["npm", "run", "start:prod"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    depends_on:
      - backend
    ports:
      - "4173:4173"
    command: ["npm", "run", "preview", "--", "--host", "0.0.0.0"]
volumes:
  pgdata:
