export const brands = [
  'Harina P.A.N.', 'Maggi', 'Las Llaves', 'Rosal', 'Los Andes', 'Mavesa', 'Kraft', 'Coca-Cola', 'Pepsi', 'Nestlé',
  'Nucita', 'Chips', 'Toddy', 'Flips', 'Savoy', 'Pirulin', 'Susy', 'Galletas Cocosette', 'Choco Milk', 'Natilla',
  'Frica', 'Plumrose', 'La Lucha', 'Frescolita', 'Enriko', 'Munchi', 'Tigo', 'Capri', 'Amanecer', 'Sello Rojo', 'Brasil',
  'Espiga Dorado', 'Santo Melao', 'Montalbán', 'Carabobo', 'San Simón', 'Purísima', 'Los Andes', 'Pasta Primor',
  'Polar', 'Cerelac', 'Arepas Doña Emilia', 'Sukø', 'Snackip', 'Cocosette', 'Milky Way', 'Nestum', 'Maltín Polar',
  'Galletas Marilú', 'Hit', 'Freskolita', 'Kas', 'Zucaritas', 'Charmy', 'Upaca', 'Tip-Top', 'La Católica', 'Pastas Sindoni',
  'Ron Santa Teresa', 'Café Madrid', 'Minalba', 'Fundación Bigott', 'Pantín', 'Dulces Criollos', 'Ron Diplomático',
  'Dulces Famosos', 'Diana', 'Industrias Diana', 'Galletera Gama', 'Pastas Capri', 'Café El Peñón', 'Kekito', 'Ovomaltina',
  'Café Imperial', 'Dulce Tiempo', 'Morochas', 'Jugo Yukery', 'Nestlé Savoy', 'ST Moriz', 'Underwood', 'Frizt', 'Sun cola',
  'Frito Lay', 'Yorriz', 'Chaos', 'Rikos', 'Chupi Chupi', 'Chocochitas', 'Pingüinitos', 'Canilla', 'Super Canilla',
  'Lluvia de Oro', 'Dulces El Rey', 'Chuchería El Dulce', 'Manicería El Tigre', 'Pekitas', 'Fruty', 'Chocomenta',
  'Coco Loco', 'Mi Galleta', 'Bon Bon', 'Tropical', 'Golden Mix', 'Lácteos La Arboleda', 'Mamá Goya', 'Marilú',
  'Tío Rico', 'Café San Domingo', 'Torticas', 'Riko Dulce', 'Panrico', 'Kraker', 'Bimbo Venezuela', 'Maní Crocante',
  'ArepaFit', 'Los Tíos', 'Paisa', 'Café Flor de Patria', 'Santa Cruz', 'Tropicalia', 'Leche Campo Real', 'Chocodots',
  'Chispitas', 'Canelitas', 'Torcán', 'Ron Carúpano', 'Casanova', 'Pastas Ronco', 'Leche Doña Lechera', 'Nevazucar',
  'Caroreña', 'La Montserratina', 'Alpina Venezuela', 'Pastas Sindoni', 'La Estancia', 'Fressco', 'Ron Pampero',
  'Aceite Mazeite', 'Aceite La Yaya', 'El Cocinero', 'Pastor', 'La Giralda', 'Vinos Pomar', 'Helados EFE',
  'Chicha La Carajita', 'Tropical Chips', 'Maní TropiSnack', 'Dulces Mary', 'Café Amanecer', 'Arroz Mary',
  'Arroz Diana', 'Los Compadres', 'Doña Emilia', 'CremHelado', 'Chocolate El Rey', 'Mango Mix', 'Nuggets Suavestar',
  'Deli Rico', 'Helados Gelato', 'Grano de Oro', 'Queso San Antonio', 'La Traviata', 'Colonia Tovar', 'Miel Oro Mel',
  'Vino Santa Ana', 'Cerveza Zulia', 'Galletas Don Goyo', 'Chiclets Adams', 'Frutas Chuchazo', 'Chocolates Anthon',
  'Harina Juana', 'Harina Robin Hood', 'Harina Sol de Oro', 'Harina Mazorca', 'Harina El Rey', 'Molinos Nacionales (MONACA)',
  'Harina La Espiga', 'Harina de Trigo P.A.N.', 'Pastas Allegra', 'Pastas La Especialista', 'Pastas Gran Señora',
  'Pastas La Suprema', 'Pastas Monticello', 'Pastas Amore', 'Pastas Florentino', 'Pastas Linda', 'Pastas Sana',
  'Pastas Frescarini', 'Pastas Venezolanas', 'Leche Campestre', 'Leche Los Andes', 'Leche Carabobo', 'Leche La Montserratina',
  'Leche Lactovisoy', 'Leche Alpina Venezuela', 'Leche Montalbán', 'Leche El Tunal', 'Leche Lácteos Torondoy',
  'Leche La Arboleda', 'Leche Cabaña', 'Leche Central Madeirense', 'Leche San Antonio', 'Leche Colina', 'Leche Parmalat',
  'Quesos Carora', 'Harina Los Cocineros', 'Harina Santa Cruz', 'Harina Primavera', 'Harina Dorada', 'Aceite Tropical',
  'Pastas Caracas', 'Pastas Rivoli', 'Harina Del Campo', 'Harina Elite', 'Harina La Favorita', 'Lácteos El Granero',
  'Harina Triguisar', 'Pastas Rústicas', 'Harina Panadera Plus', 'Harina Miraflores', 'Harina Oro Pan', 'Harina Trigal de Oro',
  'Harina Gran Pan', 'Harina La Panificadora', 'Pastas El Faro', 'Harina El Molino', 'Harina Los Andes',
  'Harina Valle Verde', 'Leche Bellavista', 'Leche Cantagallo', 'Leche Doña Clara', 'Leche Primavera', 'Dove', 'Rexona', 'Protex', 'Palmolive', 'Neko', 'Lux', 'Dial', 'Camay', 'Irish Spring', 'Savital', 'Jabón Las Llaves', 'Le Sancy', 'Jabón Cariño', 'Johnson & Johnson', 'Gorilla Snot', 'Eco Styler', 'Gelatina Moco de Gorila', 'Wetline', 'Studio Line', 'Alberto VO5', 'Pantene', 'Suave Professionals', 'Got2b', 'Tresemmé', 'American Crew', 'Cantu', 'Reuzel', 'Old Spice', 'Aussie', 'LA Looks', 'Axe', 'Sebastian Gel Forte', 'Redken Brews', 'Bed Head by Tigi', 'Lindt', 'Ferrero Rocher', 'Hershey\'s', 'Cadbury', 'Toblerone', 'KitKat', 'Snickers', 'Mars', 'Milky Way', "M&M's", 'Twix', 'Nestlé Crunch', 'Dove Chocolate', 'Godiva', 'Guylian', 'Thorntons', 'Ghirardelli', 'Kinder', 'Ritter Sport', 'Chocolates El Rey', 'Savoy', 'Mondelez', 'Chocolates St. Moritz', 'Valrhona', "Green & Black's", 'Dagoba', 'Cacao Real', 'Leonidas', 'Venchi', 'Pantene', 'Head & Shoulders', 'Garnier Fructis', 'Tresemmé', 'Dove', 'Herbal Essences', "L'Oréal Paris Elvive", 'Sunsilk', 'Sedal', 'Clear', 'Johnson & Johnson', 'Palmolive', 'Suave', 'Aussie', 'OGX', 'Kérastase', 'Matrix Biolage', 'Moroccanoil', 'Redken', 'CHI', 'Paul Mitchell', 'Revlon', 'Batiste', 'SheaMoisture', 'Cantu', 'Maui Moisture', 'Alberto VO5', 'Sebastian', 'Nexxus', 'BioSilk', 'Always', 'Kotex', 'Nosotras', 'Stayfree', 'Carefree', 'Libresse', 'Saba', 'Evax', 'Naturella', 'Bella', 'Tena', 'Depend', 'Fem', 'Poise', 'Intimus', 'Unisept', 'PantyFresh', 'Vicky', 'Cora', 'Lola', 'Organyc', 'Natracare', 'Veeda', 'Rael', 'Rexona', 'Dove', 'Nivea', 'Axe', 'Old Spice', 'Secret', 'Degree', 'Speed Stick', 'Lady Speed Stick', 'Arrid', 'Suave', 'Right Guard', 'Mitchum', 'Ban', 'Certain Dri', "Tom's of Maine", 'Crystal', 'Arm & Hammer', 'Native', "Schmidt's", 'Soft & Dri', 'Gillette', 'Sure', 'Adidas', 'Fa', 'Amway G&H', 'Avon On Duty', 'Red Bull', 'Monster', 'Rockstar', 'Burn', 'Volt', 'Bang', 'C4 Energy', 'Reign', 'Full Throttle', 'NOS', 'Adrenaline Rush', 'Amp Energy', '5-hour Energy', 'Power Horse', 'Black Energy', 'V Energy', 'Xyience', 'Xtend', 'Rip It', 'Dark Dog', 'Hype', 'Enerzone', 'Warrior Energy', 'Cobra Energy Drink', 'Guru', 'Vive 100', 'Speed max', 'Gillette', 'Schick', 'BIC', 'Wilkinson Sword', "Harry's", 'Dollar Shave Club', 'Dorco', 'Feather', 'Merkur', 'Philips Norelco', 'Braun', 'Panasonic', 'Wahl', 'Remington', 'Bevel', 'Astra', 'Personna', 'Leaf Shave', 'Henson Shaving', 'Van Der Hagen', 'King C. Gillette', 'Barbasol', 'Edwin Jagger'

]
